#   #dayzone, nightzone average temperature / humidity value
- platform: min_max
  name: Temperatura
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.dayzone_temperature_0
    - sensor.TV01_temp
    - sensor.TV02_temp
    - sensor.TV03_temp
    - sensor.TV04_temp
    - sensor.TV05_temp
    - sensor.TV06_temp
    - sensor.TV07_temp

#rollershutters average position
- platform: min_max
  name: cover mean pos
  type: mean
  entity_ids: 
    - cover.rs01
    - cover.rs02
    - cover.rs03
    - cover.rs04
    - cover.rs05
    - cover.rs06