# region SENSOR SYSTEMMONITOR
- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: memory_use_percent
    - type: processor_use
    - type: processor_temperature
    - type: last_boot
#endregion

#region platform STATISTICS
- platform: statistics
  name: "stat memory_use"
  entity_id: sensor.memory_use_percent
  sampling_size: 30
  max_age:
    minutes: 30
- platform: statistics
  name: "stat disk_use"
  entity_id: sensor.disk_use_percent
  sampling_size: 30
  max_age:
    minutes: 30
- platform: statistics
  name: "stat processor_use"
  entity_id: sensor.processor_use
  sampling_size: 75
  max_age:
    minutes: 30
- platform: statistics
  name: "stat processor_temperature"
  entity_id: sensor.processor_temperature
  sampling_size: 100
  max_age:
    minutes: 30
#endregion