kiosk_mode:
  hide_header: false
  hide_sidebar: true
  hide_menubutton: true
  hide_overflow: true
  user_settings:
    - users:
        - kairoshub
        - utente
        - user
      hide_header: false
      hide_sidebar: true
      hide_menubutton: true
      hide_overflow: true

button_card_templates: !include hakairos-configuration/frontend/components/button_card_templates.yaml

views:
  - title: HOME
    path: home
    panel: true
    style: |
      #view {
        padding-left: 1% !important;
        padding-right: 1% !important;
      }
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/components/theme/header.yaml
          - type: horizontal-stack
            cards:
              - !include hakairos-configuration/frontend/components/theme/body_col_1.yaml
              - !include hakairos-configuration/frontend/components/theme/body_col_2.yaml
          - !include hakairos-configuration/frontend/components/theme/footer.yaml
  - title: CLIMA
    path: clima
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima.yaml
  - title: TAPPARELLE
    path: tapparelle
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/rollers.yaml
  - title: LUCI
    path: luci
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights.yaml
  - title: IMPOSTAZIONI
    path: impostazioni
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings.yaml
  - title: ASSISTENZA
    path: assistenza
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/assistance.yaml
  # - title: DOCUMENTAZIONE
  #   path: documentation
  #   panel: true
  #   visible: false
  #   cards:
  #     - type: vertical-stack
  #       cards:
  #         - !include hakairos-configuration/frontend/panels/docs.yaml
  - title: Programma 1
    path: clima-p1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/programs/prog1.yaml
  - title: Programma 2
    path: clima-p2
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/programs/prog2.yaml
  - title: Programma 3
    path: clima-p3
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/programs/prog3.yaml
  - title: Programma 4
    path: clima-p4
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/clima/programs/prog4.yaml
  - path: notification
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/notification.yaml
  - path: device-status
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/device_status.yaml
  - path: impostazioni-tapparelle
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/tapparelle.yaml
  - path: impostazioni-riscaldamento
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/riscaldamento.yaml
  - path: impostazioni-zone
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/zones.yaml
  - path: impostazioni-alexa
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/alexa/alexa.yaml
  - path: impostazioni-luci
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/luci.yaml
  - path: impostazioni-scenari
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/scenes.yaml
  - path: impostazioni-associa
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/associa.yaml

  - path: rollers-program1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/rollers/p1.yaml
  - path: lights-program1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/programs/p1.yaml
  - path: lights-program2
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/programs/p2.yaml
  - path: lights-nightzone-room1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/nightzone/room1.yaml
  - path: lights-nightzone-room2
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/nightzone/room2.yaml
  - path: lights-nightzone-room3
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/nightzone/room3.yaml
  - path: lights-nightzone-room4
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/nightzone/room4.yaml
  - path: lights-dayzone-room1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/dayzone/room1.yaml
  - path: lights-dayzone-room2
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/dayzone/room2.yaml
  - path: lights-dayzone-room3
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/dayzone/room3.yaml
  - path: lights-outdoor-room1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/outdoor/room1.yaml
  - path: lights-outdoor-room2
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/outdoor/room2.yaml
  - path: lights-outdoor-room3
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/outdoor/room3.yaml
  - path: lights-outdoor-room4
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/outdoor/room4.yaml
  - path: lights-nightzone-program1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/programs/prog1/nightzone.yaml
  - path: lights-dayzone-program1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/programs/prog1/dayzone.yaml
  - path: lights-outdoor-program1
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/programs/prog1/outdoor.yaml
  - path: lights-nightzone-program2
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/programs/prog2/nightzone.yaml
  - path: lights-dayzone-program2
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/programs/prog2/dayzone.yaml
  - path: lights-outdoor-program2
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/lights/programs/prog2/outdoor.yaml
  - path: settings-dayscene-lights-nightzone
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/luci/day_scene/nightzone.yaml
  - path: settings-dayscene-lights-dayzone
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/luci/day_scene/dayzone.yaml
  - path: settings-dayscene-lights-outdoor
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/luci/day_scene/outdoor.yaml
  - path: settings-athomescene-lights-nightzone
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/luci/athome_scene/nightzone.yaml
  - path: settings-athomescene-lights-dayzone
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/luci/athome_scene/dayzone.yaml
  - path: settings-athomescene-lights-outdoor
    panel: true
    visible: false
    cards:
      - type: vertical-stack
        cards:
          - !include hakairos-configuration/frontend/panels/settings/luci/athome_scene/outdoor.yaml
