
title: Casa
views:
  - path: home
    title: ''
    theme: kairoshome - light
    icon: mdi:home-assistant
    type: panel
    badges:
      - entity: zone.home
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: weather-forecast
                entity: weather.casa
                theme: kairoshome - light
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                cards:
                  - type: button
                    tap_action:
                      action: toggle
                    entity: input_boolean.at_home
                    icon: mdi:home
                    theme: kairoshome - light
                  - type: button
                    tap_action:
                      action: toggle
                    entity: input_boolean.night
                    icon: mdi:weather-night
                    theme: kairoshome - light
              - type: horizontal-stack
                cards:
                  - type: entity
                    entity: sensor.temperatura
                    icon: mdi:temperature-celsius
                    theme: kairoshome - light
                  - type: entity
                    entity: sensor.umidita
                    icon: mdi:water-percent
              - type: horizontal-stack
                cards:
                  - type: button
                    tap_action:
                      action: toggle
                    entity: input_boolean.heater_auto
                    show_state: false
                    icon: mdi:refresh-auto
                    show_name: true
                    name: Riscaldamento auto
                    theme: kairoshome - light
                  - type: gauge
                    entity: sensor.em_consumo
                    min: 0
                    max: 3200
                    name: Consumo
                    theme: kairoshome - light
          - type: vertical-stack
            cards:
              - type: thermostat
                entity: climate.riscaldamento
                theme: kairoshome - light
                name: Riscaldamento
  - icon: mdi:radiator
    theme: kairoshome - light
    type: panel
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                cards:
                  - type: markdown
                    content: Gestione riscaldamento
                    title: Riscaldamento
                    theme: kairoshome - light
                  - type: entities
                    entities:
                      - entity: input_boolean.heater_auto
                    title: Programma
                    theme: kairoshome - light
                  - type: button
                    tap_action:
                      action: none
                    show_icon: false
                    show_name: false
                    theme: kairoshome - light
              - type: horizontal-stack
                cards:
                  - type: button
                    tap_action:
                      action: toggle
                    entity: input_boolean.heater_program1
                    show_state: true
                    theme: kairoshome - light
                    icon_height: 30px
                  - type: button
                    tap_action:
                      action: toggle
                    entity: input_boolean.heater_program2
                    show_state: true
                    theme: kairoshome - light
                    icon_height: 30px
                  - type: button
                    tap_action:
                      action: toggle
                    entity: input_boolean.heater_program3
                    show_state: true
                    theme: kairoshome - light
                    icon_height: 30px
                  - type: button
                    tap_action:
                      action: toggle
                    entity: input_boolean.heater_program4
                    show_state: true
                    theme: kairoshome - light
                    icon_height: 30px
              - type: horizontal-stack
                cards:
                  - type: entity
                    entity: input_number.temperature_period1
                    name: Temp comfort
                    theme: kairoshome - light
                    unit: 째C
                  - type: entity
                    entity: input_number.temperature_period2
                    theme: kairoshome - light
                    unit: 째C
                    name: Temp comfort
                  - type: entity
                    entity: input_number.temperature_period3
                    theme: kairoshome - light
                    unit: 째C
                    name: Temp comfort
                  - type: entity
                    entity: input_number.temperature_period4
                    theme: kairoshome - light
                    unit: 째C
                    name: Temp comfort
              - type: horizontal-stack
                cards:
                  - type: entity
                    entity: input_select.thermostat_days_period1
                    name: Giorni
                    theme: kairoshome - light
                  - type: entity
                    entity: input_select.thermostat_days_period2
                    name: Giorni
                    theme: kairoshome - light
                  - type: entity
                    entity: input_select.thermostat_days_period3
                    name: Giorni
                    theme: kairoshome - light
                  - type: entity
                    entity: input_select.thermostat_days_period4
                    name: Giorni
                    theme: kairoshome - light
              - type: horizontal-stack
                cards:
                  - type: entities
                    entities:
                      - entity: input_select.thermostat_on_period1
                        icon: mdi:calendar-clock-outline
                        name: ' Accensione'
                      - entity: input_select.thermostat_off_period1
                        icon: mdi:calendar-clock-outline
                        name: Spegnimento
                    theme: kairoshome - light
                  - type: entities
                    entities:
                      - entity: input_select.thermostat_on_period2
                        icon: mdi:calendar-clock-outline
                        name: ' Accensione'
                      - entity: input_select.thermostat_off_period2
                        icon: mdi:calendar-clock-outline
                        name: Spegnimento
                    theme: kairoshome - light
                  - type: entities
                    entities:
                      - entity: input_select.thermostat_on_period3
                        icon: mdi:calendar-clock-outline
                        name: ' Accensione'
                      - entity: input_select.thermostat_off_period3
                        icon: mdi:calendar-clock-outline
                        name: Spegnimento
                    theme: kairoshome - light
                  - type: entities
                    entities:
                      - entity: input_select.thermostat_on_period4
                        icon: mdi:calendar-clock-outline
                        name: ' Accensione'
                      - entity: input_select.thermostat_off_period4
                        icon: mdi:calendar-clock-outline
                        name: Spegnimento
                    theme: kairoshome - light
  - icon: mdi:cog
    theme: kairoshome - light
    badges: []
    cards: []
  - icon: mdi:shield-account
    visible:
      - user: 08ff7e68f9404962b77a833bab1ce0fb
    theme: kairoshome - light
    badges: []
    cards: []
