type: "custom:button-card"
template: settings_grid
custom_fields:
  header:
    card:
      type: "custom:button-card"
      template: header_page_text
      name: "IMPOSTAZIONI"
      label: "Impostazioni /"
      icon: "mdi:cog"
  content:
    card:
      type: grid
      columns: 4
      square: false
      cards:
        - type: conditional
          conditions:
            - entity: input_boolean.heating_integration
              state: "on"
          card:
            type: "custom:button-card"
            template: settings_card
            icon: "mdi:thermometer"
            name: "Riscaldamento"
            variables:
              navigation_path: "impostazioni-riscaldamento"
        - type: conditional
          conditions:
            - entity: input_boolean.roller_integration
              state: "on"
          card:
            type: "custom:button-card"
            template: settings_card
            icon: mdi:window-shutter
            name: Tapparelle
            variables:
              navigation_path: "impostazioni-tapparelle"
        - type: conditional
          conditions:
            - entity: input_boolean.light_integration
              state: "on"
          card:
            type: "custom:button-card"
            template: settings_card
            icon: "mdi:lightbulb"
            name: "Luci"
            variables:
              navigation_path: "impostazioni-luci"
        - type: "custom:button-card"
          template: settings_card
          icon: "mdi:dots-grid"
          name: "Zone"
          variables:
            navigation_path: "impostazioni-zone"
        - type: conditional
          conditions:
            - entity: input_boolean.alexa_integration
              state: "on"
          card:
            type: "custom:button-card"
            template: settings_card
            icon: "mdi:amazon-alexa"
            name: "Alexa"
            variables:
              navigation_path: "impostazioni-alexa"
        - type: "custom:button-card"
          template: settings_card
          icon: "mdi:cog"
          name: "Sistema"
          variables:
            navigation_path: impostazioni-sistema
