#Temperatura Media Valvole
- platform: min_max
  name: Temperatura
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TZ100
    - sensor.TZ200
#Media Temperatura Zona Notte
- platform: min_max
  name: TZ100
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH1001_temp
    - sensor.TZ101
    - sensor.TZ102
    - sensor.TZ103
    - sensor.TZ104
#Media Temperatura Zona Giorno
- platform: min_max
  name: TZ200
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH2001_temp
    - sensor.TZ201
    - sensor.TZ202
    - sensor.TZ203
