#Media Temperatura Soggiorno
- platform: min_max
  name: TZ201
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.dayzone_temperature_0
    - sensor.TV04_temp
    - sensor.TV05_temp
    - sensor.TH2011_temp
    - sensor.TV2011_temp
    - sensor.TV2012_temp
#Media Temperatura Cucina
- platform: min_max
  name: TZ202
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TV06_temp
    - sensor.TH2021_temp
    - sensor.TV2021_temp
    - sensor.TV2022_temp
#Media Temperatura Bagno 2
- platform: min_max
  name: TZ203
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH2031_temp
    - sensor.TV2031_temp
    - sensor.TV2032_temp