#####
##### HA-CUSTOM-EVENTS Configuration
#####
events:
  - event: HA_STARTUP_COMPLETE
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_CONSUMER_START
      - event: HAKAFKA_PRODUCER_START
  - event: HA_SHUTDOWN_REQUEST
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_CONSUMER_STOP
      - event: HAKAFKA_PRODUCER_STOP
  - event: HAKAFKA_CONSUMER_START
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_PRODUCER_START
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_CONSUMER_STOP
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_PRODUCER_STOP
    platform: HAKAFKA
    type: dispatcher
  - event: INBOUND_EVENT
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO"
  - event: HAKAFKA_PRODUCER_PRODUCE
    platform: HAKAFKA
    type: dispatcher
  - event: HA_SYSTEM_ENTITIES_ALIGN
    platform: HASSIO_STATE
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO_ENTITY_ALIGN"
  - event: HA_SYSTEM_COMMAND_ALING
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO_ENTITY_ALIGN"
        data:
          - event: line_1_on
          - event: line_1_off
          - event: line_2_on
          - event: line_2_off
targets:
  - target: binary_sensor.s7_state
    events: 
      - event: blackout
        level: ALERT
        message: Attenzione, Serra 7 - blackout in corso!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO" 
      - event: windows_side_anomaly
        level: ALERT
        message: Attenzione, Serra 7 - Anomalia finestre laterali!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: windows_top_anomaly
        level: ALERT
        message: Attenzione, Serra 7 - Anomalia Colmi!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: off
        level: NOTICE
        message: Anomalia Serra 7 rientrata. Automazioni finestre ripristinate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: binary_sensor.s8_state
    events: 
      - event: blackout
        level: ALERT
        message: Attenzione, Serra 8 - blackout in corso!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO" 
      - event: windows_side_anomaly
        level: ALERT
        message: Attenzione, Serra 8 - Anomalia finestre laterali!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: windows_top_anomaly
        level: ALERT
        message: Attenzione, Serra 8 - Anomalia Colmi!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"    
      - event: off
        level: NOTICE
        message: Anomalia Serra 8 rientrata. Automazioni finestre ripristinate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: sensor.w_temperature_state
    events:
      - event: cold
        level: NOTICE
        message: Attenzione, temperatura bassa (10 gradi)
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: extremely_cold
        level: ALERT
        message: Attenzione, temperatura estremamente bassa!!! (5 gradi)
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: extremely_hot
        level: ALERT
        message: Attenzione, temperatura estremamente alta!!! (sopra 30 gradi)
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
            data:
              - event: line_1_on
              - event: line_2_on
  - target: sensor.s7_temperature_state
    events:
      - event: TEMP_EXTREMELY_LOW
        level: ALERT
        message: Serra 7 - Temperatura estremamente bassa! Finestre in chiusura totale.
      - event: TEMP_EXTREMELY_HIGH
        level: ALERT
        message: Serra 7 - Temperatura estremamente alta! Finestre in apertura totale.
  - target: sensor.s8_temperature_state
    events:
      - event: TEMP_EXTREMELY_LOW
        level: ALERT
        message: Serra 8 - Temperatura estremamente bassa! Finestre in chiusura totale.
      - event: TEMP_EXTREMELY_HIGH
        level: ALERT
        message: Serra 8 - Temperatura estremamente alta! Finestre in apertura totale.




  - target: binary_sensor.line_1_state
    events:
      - event: NOTICE_LINE_1_ON
        level: NOTICE
        message: Irrigazione linea 1 ON
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: NOTICE_LINE_1_OFF
        level: NOTICE
        message: Irrigazione linea 1 OFF
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: binary_sensor.line_2_state
    events:
      - event: NOTICE_LINE_2_ON
        level: NOTICE
        message: Irrigazione linea 2 ON
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: NOTICE_LINE_2_OFF
        level: NOTICE
        message: Irrigazione linea 2 OFF
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      
  - target: scripts.ececution
    events: 
      - event: ENTITY_METRICS_COLLECTION
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO_ENTITY_METRICS"
      - event: SYSTEM_METRICS_COLLECTION
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO_SYSTEM_METRICS"
