#####
##### HA-CUSTOM-EVENTS Configuration
#####
events:
  - event: HA_STARTUP_COMPLETE
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_CONSUMER_START
      - event: HAKAFKA_PRODUCER_START
  - event: HA_SHUTDOWN_REQUEST
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_CONSUMER_STOP
      - event: HAKAFKA_PRODUCER_STOP
  - event: HAKAFKA_CONSUMER_START
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_PRODUCER_START
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_CONSUMER_STOP
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_PRODUCER_STOP
    platform: HAKAFKA
    type: dispatcher
  - event: INBOUND_EVENT
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO"
  - event: HAKAFKA_PRODUCER_PRODUCE
    platform: HAKAFKA
    type: dispatcher
  - event: HA_SYSTEM_ENTITIES_ALIGN
    platform: HASSIO_STATE
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO_ENTITY_ALIGN"
  - event: HA_SYSTEM_COMMAND_ALING
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO_ENTITY_ALIGN"
        data:
          - event: line_1_on
          - event: line_1_off
          - event: line_2_on
          - event: line_2_off
targets:
  - target: binary_sensor.s7_state
    events: 
      - event: blackout
        level: ALERT
        message: Attenzione, Serra 7 - blackout in corso!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO" 
      - event: windows_side_anomaly
        level: ALERT
        message: Attenzione, Serra 7 - Anomalia finestre laterali!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: windows_top_anomaly
        level: ALERT
        message: Attenzione, Serra 7 - Anomalia Colmi!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: off
        level: NOTICE
        message: Anomalia Serra 7 rientrata. Automazioni finestre ripristinate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: binary_sensor.s8_state
    events: 
      - event: blackout
        level: ALERT
        message: Attenzione, Serra 8 - blackout in corso!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO" 
      - event: windows_side_anomaly
        level: ALERT
        message: Attenzione, Serra 8 - Anomalia finestre laterali!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: windows_top_anomaly
        level: ALERT
        message: Attenzione, Serra 8 - Anomalia Colmi!!! Automazioni sulle finestre disabilitate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"    
      - event: off
        level: NOTICE
        message: Anomalia Serra 8 rientrata. Automazioni finestre ripristinate.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: sensor.w_temperature_state
    events:
      - event: cold
        level: NOTICE
        message: Attenzione, temperatura bassa (10 gradi)
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: extremely_cold
        level: ALERT
        message: Attenzione, temperatura estremamente bassa!!! (5 gradi)
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: extremely_hot
        level: ALERT
        message: Attenzione, temperatura estremamente alta!!! (sopra 30 gradi)
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
            data:
              - event: line_1_on
              - event: line_2_on
  - target: sensor.w_rain_state
    events:
      - event: WE_RAINING
        level: ALERT
        message: Attenzione, Rilevata pioggia. Chiusura dei colmi delle serre in corso.
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: binary_sensor.s7_windows_top_open
    events:
      - event: "off"
        level: ALERT
        message: Attenzione, Colmi Serra 7 chiusi completamente
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: binary_sensor.s8_windows_top_open
    events:
      - event: "off"
        level: ALERT
        message: Attenzione, Colmi Serra 8 chiusi completamente
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: binary_sensor.kt_gateway_000001
    events:
      - event: "offline"
        level: TECHNICAL
        message: Attenzione, Ponte radio Serra 7 (kt_gateway_000001) OFFLINE
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: binary_sensor.kt_node_000001
    events:
      - event: "offline"
        level: TECHNICAL
        message: Attenzione, Stazione rilevamento Serra 8 (kt_node_000001) OFFLINE
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: input_boolean.system_windows_recalibration_inprogress
    events:
      - event: "deadlock"
        level: TECHNICAL
        message: Rilevato problema DEADLOCK su ricalibrazione finestre
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: "on"
        level: ALERT
        message: Inizio procedura di ricalibrazione delle finestre 
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: "off"
        level: ALERT
        message: Procedura di ricalibrazione delle finestre completata con successo
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  
      
  - target: scripts.ececution
    events: 
      - event: ENTITY_METRICS_COLLECTION
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO_ENTITY_METRICS"
      - event: SYSTEM_METRICS_COLLECTION
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO_SYSTEM_METRICS"
