#####
##### HA-CUSTOM-EVENTS Configuration
#####
events:
  - event: HA_STARTUP_COMPLETE
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_CONSUMER_START
      - event: HAKAFKA_PRODUCER_START
  - event: HA_SHUTDOWN_REQUEST
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_CONSUMER_STOP
      - event: HAKAFKA_PRODUCER_STOP
  - event: HAKAFKA_CONSUMER_START
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_PRODUCER_START
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_CONSUMER_STOP
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_PRODUCER_STOP
    platform: HAKAFKA
    type: dispatcher
  - event: INBOUND_EVENT
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO"
  - event: HAKAFKA_PRODUCER_PRODUCE
    platform: HAKAFKA
    type: dispatcher
  - event: HA_SYSTEM_ENTITIES_ALIGN
    platform: HASSIO_STATE
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO_ENTITY_ALIGN"
  - event: HA_SYSTEM_COMMAND_ALING
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO_ENTITY_ALIGN"
        data:
          - event: automationEventOnLine1
          - event: automationEventOffLine1
          - event: automationEventOnLine2
          - event: automationEventOffLine2
          - event: automationEventOffPump
  - event: automationEventOnLine1
    platform: HASSIO_EVENT
    type: dispatcher
    label: "Accendi irrigazione Linea 1"
  - event: automationEventOnLine2
    platform: HASSIO_EVENT
    type: dispatcher
    label: "Accendi irrigazione Linea 2"
  - event: automationEventOffLine1
    platform: HASSIO_EVENT
    type: dispatcher
    label: "Spegni irrigazione Linea 1"
  - event: automationEventOffLine2
    platform: HASSIO_EVENT
    type: dispatcher
    label: "Spegni irrigazione Linea 2"
  - event: automationEventOffPump
    platform: HASSIO_EVENT
    type: dispatcher
    label: "Spegni irrigazione"
targets:
  - target: scripts.ececution
    events: 
      - event: ENTITY_METRICS_COLLECTION
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO_ENTITY_METRICS"
      - event: SYSTEM_METRICS_COLLECTION
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO_SYSTEM_METRICS"
  - target: input_boolean.pump_line_1
    events:
      - event: LINE_1_ON
        level: NOTICE
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: LINE_1_OFF
        level: NOTICE
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: input_boolean.pump_line_2
    events:
      - event: LINE_2_ON
        level: NOTICE
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
      - event: LINE_2_OFF
        level: NOTICE
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
  - target: input_boolean.pump_anomaly
    events:
      - event: ALERT_PUMP_ANOMALY
        level: ALERT
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO"
            data:
              - event:  automationEventOffPump
