#####
##### HA-CUSTOM-EVENTS Configuration
#####
events:
  - event: HA_STARTUP_COMPLETE
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_CONSUMER_START
        topic: "input_text.system_code"
      - event: HAKAFKA_PRODUCER_START
  - event: HA_SHUTDOWN_REQUEST
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_CONSUMER_STOP
      - event: HAKAFKA_PRODUCER_STOP
  - event: HAKAFKA_CONSUMER_START
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_PRODUCER_START
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_CONSUMER_STOP
    platform: HAKAFKA
    type: dispatcher
  - event: HAKAFKA_PRODUCER_STOP
    platform: HAKAFKA
    type: dispatcher
  - event: INBOUND_EVENT
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO"
  - event: HAKAFKA_PRODUCER_PRODUCE
    platform: HAKAFKA
    type: dispatcher
  - event: HA_SYSTEM_ENTITIES_ALIGN
    platform: HASSIO_STATE
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO_ENTITY_ALIGN"
  - event: HA_SYSTEM_COMMAND_ALING
    platform: HASSIO_EVENT
    type: listener
    callback:
      - event: HAKAFKA_PRODUCER_PRODUCE
        topic: "HASSIO_ENTITY_ALIGN"
        data:
          - event: automationEventOnCommand
          - event: automationEventOffCommand
  - event: automationEventOnCommand
    platform: HASSIO_EVENT
    type: dispatcher
    label: "An event to be dispatched"
  - event: automationEventOffCommand
    platform: HASSIO_EVENT
    type: dispatcher
    label: "An event to be dispatched"
targets:
  - target: scripts.ececution
    events: 
      - event: ENTITY_METRICS_COLLECTION
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO_ENTITY_METRICS"
      - event: SYSTEM_METRICS_COLLECTION
        callback:
          - event: HAKAFKA_PRODUCER_PRODUCE
            topic: "HASSIO_SYSTEM_METRICS"
