# LCZ201
- platform: mqtt
  schema: template
  name: "LCZ201"
  unique_id: "LCZ201"
  command_topic: "shellies/LZ201/color/0/set"
  state_topic: "shellies/LZ201/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true

# LCZ202
- platform: mqtt
  schema: template
  name: "LCZ202"
  unique_id: "LCZ202"
  command_topic: "shellies/LZ202/color/0/set"
  state_topic: "shellies/LZ202/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true

# LCZ203
- platform: mqtt
  schema: template
  name: "LCZ203"
  unique_id: "LCZ203"
  command_topic: "shellies/LZ203/color/0/set"
  state_topic: "shellies/LZ203/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true