# LCZ101
- platform: mqtt
  schema: template
  name: "LCZ101"
  unique_id: "LCZ101"
  command_topic: "shellies/LZ101/color/0/set"
  state_topic: "shellies/LZ101/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true

# LCZ102
- platform: mqtt
  schema: template
  name: "LCZ102"
  unique_id: "LCZ102"
  command_topic: "shellies/LZ102/color/0/set"
  state_topic: "shellies/LZ102/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true

# LCZ103
- platform: mqtt
  schema: template
  name: "LCZ103"
  unique_id: "LCZ103"
  command_topic: "shellies/LZ103/color/0/set"
  state_topic: "shellies/LZ103/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true

# LCZ104
- platform: mqtt
  schema: template
  name: "LCZ104"
  unique_id: "LCZ104"
  command_topic: "shellies/LZ104/color/0/set"
  state_topic: "shellies/LZ104/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true