# LCZ301
- platform: mqtt
  schema: template
  name: "LCZ301"
  unique_id: "LCZ301"
  command_topic: "shellies/LZ301/color/0/set"
  state_topic: "shellies/LZ301/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true

# LCZ302
- platform: mqtt
  schema: template
  name: "LCZ302"
  unique_id: "LCZ302"
  command_topic: "shellies/LZ302/color/0/set"
  state_topic: "shellies/LZ302/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true

# LCZ303
- platform: mqtt
  schema: template
  name: "LCZ303"
  unique_id: "LCZ303"
  command_topic: "shellies/LZ303/color/0/set"
  state_topic: "shellies/LZ303/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true

# LCZ304
- platform: mqtt
  schema: template
  name: "LCZ304"
  unique_id: "LCZ304"
  command_topic: "shellies/LZ304/color/0/set"
  state_topic: "shellies/LZ304/color/0/status"
  command_on_template: >
    {"turn": "on"
    {%- if brightness is defined -%}
    , "gain": {{brightness | float | multiply(0.3922) | round(0)}}
    {%- endif -%}
    {%- if red is defined and green is defined and blue is defined -%}
    , "red": {{ red }}, "green": {{ green }}, "blue": {{ blue }}
    {%- endif -%}
    {% if white_value is defined %}
    , "white": {{ white_value }}
    {% endif %}
    }
  command_off_template: '{"turn":"off"}'
  state_template: >
    {% if value_json.ison %}
      on
    {% else %}
      off
    {% endif %}
  brightness_template: "{{ value_json.gain | float | multiply(2.55) | round(0) }}"
  red_template: '{{ value_json.red }}'
  green_template: '{{ value_json.green }}'
  blue_template: '{{ value_json.blue }}'
  white_value_template: '{{ value_json.white }}'
  qos: 0
  retain: true