#####
##### HA-KAFKA Configuration
#####
ssl_context:
  ssl_certpath: "/opt/ha-cert"
  ssl_cafile: "ca-cert"
  ssl_certfile: "cert-signed"
  ssl_keyfile: "private-key"
  ssl_password: "LinkedSolutions"
# sasl_context:
#   sasl_mechanism: "PLAIN"
#   sasl_plain_username: "zzzz"
#   sasl_plain_password: "zzzzz-secret"
producers:
  - host: quattrostagioni.linkedsolutions.it
    port: 9093
    topic: "HASSIO"
    security: "ssl"
  - host: quattrostagioni.linkedsolutions.it
    port: 9093
    topic: "HASSIO_ENTITY_ALIGN"
    security: "ssl"
  - host: quattrostagioni.linkedsolutions.it
    port: 9093
    topic: "HASSIO_ENTITY_METRICS"
    security: "ssl"
  - host: quattrostagioni.linkedsolutions.it
    port: 9093
    topic: "HASSIO_SYSTEM_METRICS"
    security: "ssl"
  - host: quattrostagioni.linkedsolutions.it
    port: 9093
    topic: "HASSIO_SETTINGS"
    security: "ssl"
consumers:
  - host: quattrostagioni.linkedsolutions.it
    port: 9093
    topic: KAIROS_XXXXXX
    group: "hassio"
    security: "ssl"
