- platform: template
  sensors:
    rz101:
      value_template: >
        {% set cover0 = state_attr('sensor.rs01', 'pos') | int(default=-1) %}
        {% set cover1 = state_attr('sensor.rs1011', 'pos') | int(default=-1) %}
        {% set cover2 = state_attr('sensor.rs1012', 'pos') | int(default=-1) %}
        {% set values = [cover0, cover1, cover2] %}
        {% set ns = namespace(count = 0, sum=0) %}
        {% for value in values | reject('lt', 0) %}
          {% set ns.count = ns.count +1 %}
          {% set ns.sum = ns.sum + value %}
        {% endfor %}
        {% if ns.count > 0 %}
          {{ ns.sum / ns.count }}
        {% else %}
          unknown
        {% endif %}
    rz102:
      value_template: >
        {% set cover0 = state_attr('sensor.rs02', 'pos') | int(default=-1) %}
        {% set cover1 = state_attr('sensor.rs1021', 'pos') | int(default=-1) %}
        {% set cover2 = state_attr('sensor.rs1022', 'pos') | int(default=-1) %}
        {% set values = [cover0, cover1, cover2] %}
        {% set ns = namespace(count = 0, sum=0) %}
        {% for value in values | reject('lt', 0) %}
          {% set ns.count = ns.count +1 %}
          {% set ns.sum = ns.sum + value %}
        {% endfor %}
        {% if ns.count > 0 %}
          {{ ns.sum / ns.count }}
        {% else %}
          unknown
        {% endif %}
    rz103:
      value_template: >
        {% set cover0 = state_attr('sensor.rs03', 'pos') | int(default=-1) %}
        {% set cover1 = state_attr('sensor.rs1031', 'pos') | int(default=-1) %}
        {% set cover2 = state_attr('sensor.rs1032', 'pos') | int(default=-1) %}
        {% set values = [cover0, cover1, cover2] %}
        {% set ns = namespace(count = 0, sum=0) %}
        {% for value in values | reject('lt', 0) %}
          {% set ns.count = ns.count +1 %}
          {% set ns.sum = ns.sum + value %}
        {% endfor %}
        {% if ns.count > 0 %}
          {{ ns.sum / ns.count }}
        {% else %}
          unknown
        {% endif %}
    rz104:
      value_template: >
        {% set cover1 = state_attr('sensor.rs1041', 'pos') | int(default=-1) %}
        {% set cover2 = state_attr('sensor.rs1042', 'pos') | int(default=-1) %}
        {% set values = [cover1, cover2] %}
        {% set ns = namespace(count = 0, sum=0) %}
        {% for value in values | reject('lt', 0) %}
          {% set ns.count = ns.count +1 %}
          {% set ns.sum = ns.sum + value %}
        {% endfor %}
        {% if ns.count > 0 %}
          {{ ns.sum / ns.count }}
        {% else %}
          unknown
        {% endif %}