#Media Posizione Tapparelle Soggiorno
- platform: min_max
  name: RZ201
  type: mean
  entity_ids:
    - sensor.rs04_pos
    - sensor.rs05_pos
    - sensor.rs2011_pos
    - sensor.rs2012_pos
#Media Posizione Tapparelle Cucina
- platform: min_max
  name: RZ202
  type: mean
  entity_ids:
    - sensor.rs06_pos
    - sensor.rs2021_pos
    - sensor.rs2022_pos
#Media Posizione Tapparelle Bagno 2
- platform: min_max
  name: RZ203
  type: mean
  entity_ids:
    - sensor.rs2031_pos
    - sensor.rs2032_pos
