#Media Posizione Tapparelle Soggiorno
- platform: min_max
  name: RP201
  type: mean
  entity_ids:
    - cover.RS2011
    - cover.RS2012
#Media Posizione Tapparelle Cucina
- platform: min_max
  name: RP202
  type: mean
  entity_ids:
    - cover.RS2021
    - cover.RS2022
#Media Posizione Tapparelle Bagno 2
- platform: min_max
  name: RP203
  type: mean
  entity_ids:
    - cover.RS2031
    - cover.RS2032