#Media Posizione Tapparelle Letto 1
- platform: min_max
  name: RZ101
  type: mean
  entity_ids:
    - sensor.rs01_pos
    - sensor.rs1011_pos
    - sensor.rs1012_pos
#Media Posizione Tapparelle Letto 2
- platform: min_max
  name: RZ102
  type: mean
  entity_ids:
    - sensor.rs02_pos
    - sensor.rs1021_pos
    - sensor.rs1022_pos
#Media Posizione Tapparelle Letto 3
- platform: min_max
  name: RZ103
  type: mean
  entity_ids:
    - sensor.rs03_pos
    - sensor.rs1031_pos
    - sensor.rs1032_pos
#Media Posizione Tapparelle Bagno 1
- platform: min_max
  name: RZ104
  type: mean
  entity_ids:
    - sensor.rs1041_pos
    - sensor.rs1042_pos