- alias: Hassio start routine
  trigger:
    event: start
    platform: homeassistant
  action:
    - delay: 00:00:30
    - event: HA_STARTUP_COMPLETE
- alias: RUN Entity metrics collect
  trigger:
    platform: time_pattern
    hours: "/1"
  action:
    - service: shell_command.entity_metrics
# - alias: HA entity metrics collection
#   trigger: 
#     platform: mqtt
#     topic: "metrics/entities"
#   action: 
#     - event: HA_SCRIPT_EVENT
#       event_data:
#         payload: "{{ trigger.payload }}"
- alias: RUN System metrics collect
  trigger:
    platform: time_pattern
    hours: "/1"
  action:
    - service: shell_command.system_metrics
# - alias: HA system metrics collection
#   trigger: 
#     platform: mqtt
#     topic: "metrics/system"
#   action: 
#     - event: HA_SCRIPT_EVENT
#       event_data:
#         payload: "{{ trigger.payload }}"
- alias: Hassio shutdown routine
  trigger:
    event: shutdown
    platform: homeassistant
  action:
    - event: HA_SHUTDOWN_REQUEST
