- alias: Hassio start routine
  trigger:
    - event: start
      platform: homeassistant
  action:
    - event: HA_SET_CONSUMER_TOPIC
    - delay: 00:00:30
    - event: HA_STARTUP_COMPLETE
    - event: AD_KAIROSHUB_STARTED
- alias: KAFKA CONSUMER SET
  trigger:
    - platform: state
      entity_id: input_text.system_code
      for: "00:15:00"
    - platform: event
      event_type: HA_SET_CONSUMER_TOPIC
  action:
    - service: mqtt.publish
      data_template:
        topic: "kairostech/command"
        payload: "SET_CONSUMER_TOPIC_{{ states('input_text.system_code') }}"
- alias: RUN Entity metrics collect
  trigger:
    platform: time_pattern
    hours: "/1"
  action:
    - service: shell_command.entity_metrics
- alias: HA entity metrics collection
  trigger:
    platform: mqtt
    topic: "metrics/entities"
  action:
    - event: HA_SCRIPT_EVENT
      event_data:
        payload: "{{ trigger.payload }}"
- alias: SYSTEM METRICS
  trigger:
    platform: time_pattern
    minutes: "/30"
  action:
    - event: AD_SYSTEM_METRICS
- alias: ENTITY METRICS
  trigger:
    platform: time_pattern
    minutes: /15
  action:
    event: "AD_ENTITY_METRICS"
- alias: HA system metrics collection
  trigger:
    platform: mqtt
    topic: "metrics/system"
  action:
    - event: HA_SCRIPT_EVENT
      event_data:
        payload: "{{ trigger.payload }}"
- alias: Hassio shutdown routine
  trigger:
    event: shutdown
    platform: homeassistant
  action:
    - event: HA_SHUTDOWN_REQUEST
