- alias: Hassio start routine
  trigger:
    event: start
    platform: homeassistant
  action:
    - delay: 00:00:30
    - event: HA_STARTUP_COMPLETE
- alias: Hassio shutdown routine
  trigger:
    event: shutdown
    platform: homeassistant
  action:
    - event: HA_SHUTDOWN_REQUEST
