#RS2011
- platform: mqtt
  unique_id: "rs2011"
  name: "RS2011"
  command_topic: "shellies/RS2011/roller/0/command"
  position_topic: "shellies/RS2011/roller/0/pos"
  set_position_topic: "shellies/RS2011/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS2012
- platform: mqtt
  unique_id: "rs2012"
  name: "RS2012"
  command_topic: "shellies/RS2012/roller/0/command"
  position_topic: "shellies/RS2012/roller/0/pos"
  set_position_topic: "shellies/RS2012/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS2021
- platform: mqtt
  unique_id: "rs2021"
  name: "RS2021"
  command_topic: "shellies/RS2021/roller/0/command"
  position_topic: "shellies/RS2021/roller/0/pos"
  set_position_topic: "shellies/RS2021/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS2022
- platform: mqtt
  unique_id: "rs2022"
  name: "RS2022"
  command_topic: "shellies/RS2022/roller/0/command"
  position_topic: "shellies/RS2022/roller/0/pos"
  set_position_topic: "shellies/RS2022/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS2031
- platform: mqtt
  unique_id: "rs2031"
  name: "RS2031"
  command_topic: "shellies/RS2031/roller/0/command"
  position_topic: "shellies/RS2031/roller/0/pos"
  set_position_topic: "shellies/RS2031/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS2032
- platform: mqtt
  unique_id: "rs2032"
  name: "RS2032"
  command_topic: "shellies/RS2032/roller/0/command"
  position_topic: "shellies/RS2032/roller/0/pos"
  set_position_topic: "shellies/RS2032/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1