#RS1011
- platform: mqtt
  unique_id: "rs1011"
  name: "RS1011"
  command_topic: "shellies/RS1011/roller/0/command"
  position_topic: "shellies/RS1011/roller/0/pos"
  set_position_topic: "shellies/RS1011/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS1012
- platform: mqtt
  unique_id: "rs1012"
  name: "RS1012"
  command_topic: "shellies/RS1012/roller/0/command"
  position_topic: "shellies/RS1012/roller/0/pos"
  set_position_topic: "shellies/RS1012/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS1021
- platform: mqtt
  unique_id: "rs1021"
  name: "RS1021"
  command_topic: "shellies/RS1021/roller/0/command"
  position_topic: "shellies/RS1021/roller/0/pos"
  set_position_topic: "shellies/RS1021/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS1022
- platform: mqtt
  unique_id: "rs1022"
  name: "RS1022"
  command_topic: "shellies/RS1022/roller/0/command"
  position_topic: "shellies/RS1022/roller/0/pos"
  set_position_topic: "shellies/RS1022/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS1031
- platform: mqtt
  unique_id: "rs1031"
  name: "RS1031"
  command_topic: "shellies/RS1031/roller/0/command"
  position_topic: "shellies/RS1031/roller/0/pos"
  set_position_topic: "shellies/RS1031/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS1032
- platform: mqtt
  unique_id: "rs1032"
  name: "RS1032"
  command_topic: "shellies/RS1032/roller/0/command"
  position_topic: "shellies/RS1032/roller/0/pos"
  set_position_topic: "shellies/RS1032/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS1041
- platform: mqtt
  unique_id: "rs1041"
  name: "RS1041"
  command_topic: "shellies/RS1041/roller/0/command"
  position_topic: "shellies/RS1041/roller/0/pos"
  set_position_topic: "shellies/RS1041/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
#RS1042
- platform: mqtt
  unique_id: "rs1042"
  name: "RS1042"
  command_topic: "shellies/RS1042/roller/0/command"
  position_topic: "shellies/RS1042/roller/0/pos"
  set_position_topic: "shellies/RS1042/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1