- platform: mqtt
  unique_id: "rs01"
  name: "RS01"
  command_topic: "shellies/RS01/roller/0/command"
  position_topic: "shellies/RS01/roller/0/pos"
  set_position_topic: "shellies/RS01/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
- platform: mqtt
  unique_id: "rs02"
  name: "RS02"
  command_topic: "shellies/RS02/roller/0/command"
  position_topic: "shellies/RS02/roller/0/pos"
  set_position_topic: "shellies/RS02/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
- platform: mqtt
  unique_id: "rs03"
  name: "RS03"
  command_topic: "shellies/RS03/roller/0/command"
  position_topic: "shellies/RS03/roller/0/pos"
  set_position_topic: "shellies/RS03/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
- platform: mqtt
  unique_id: "rs04"
  name: "RS04"
  command_topic: "shellies/RS04/roller/0/command"
  position_topic: "shellies/RS04/roller/0/pos"
  set_position_topic: "shellies/RS04/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
- platform: mqtt
  unique_id: "rs05"
  name: "RS05"
  command_topic: "shellies/RS05/roller/0/command"
  position_topic: "shellies/RS05/roller/0/pos"
  set_position_topic: "shellies/RS05/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1
- platform: mqtt
  unique_id: "rs06"
  name: "RS06"
  command_topic: "shellies/RS06/roller/0/command"
  position_topic: "shellies/RS06/roller/0/pos"
  set_position_topic: "shellies/RS06/roller/0/command/pos"
  payload_available: "true"
  payload_not_available: "false"
  retain: false
  payload_open: "open"
  payload_close: "close"
  payload_stop: "stop"
  position_open: 100
  position_closed: 0
  optimistic: false
  qos: 1