#Media Temperatura Letto 1
- platform: min_max
  name: HZ101
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH1011_humidity
#Media Temperatura Letto 2
- platform: min_max
  name: HZ102
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH1021_humidity
#Media Temperatura Letto 3
- platform: min_max
  name: HZ103
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH1031_humidity
#Media Temperatura Bagno 1
- platform: min_max
  name: HZ104
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH1041_humidity