#Media Umidità
- platform: min_max
  name: Umidità
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.HM100
    - sensor.HM200
#Media Umidità Zona Notte
- platform: min_max
  name: HM100
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH1000_humidity
    - sensor.TH1011_humidity
    - sensor.TH1021_humidity
    - sensor.TH1031_humidity
    - sensor.TH1041_humidity
#Media Umidità Zona Giorno
- platform: min_max
  name: HM200
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH2000_humidity
    - sensor.TH2011_humidity
    - sensor.TH2021_humidity
    - sensor.TH2031_humidity