#Media Umidità
- platform: min_max
  name: Umidità
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.HZ100
    - sensor.HZ200
#Media Umidità Zona Notte
- platform: min_max
  name: HZ100
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH1001_humidity
    - sensor.HZ101
    - sensor.HZ102
    - sensor.HZ103
    - sensor.HZ104
#Media Umidità Zona Giorno
- platform: min_max
  name: HZ200
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH2001_humidity
    - sensor.HZ201
    - sensor.HZ202
    - sensor.HZ203