- alias: HOME TO_OFF
  trigger:
    - platform: state
      entity_id: input_boolean.at_home
      from: "on"
      to: "off"
      for: "00:00:05"
  action:
    - event: HA_ROLLERS_NOTATHOME_POSITION
    - event: HA_MANAGE_HOME_ON_OFF
      event_data:
        state: "{{ trigger.to_state.state }}"

- alias: HOME TO_ON
  trigger:
    - platform: state
      entity_id: input_boolean.at_home
      from: "off"
      to: "on"
  action:
    - event: HA_ROLLERS_ATHOME_POSITION
    - event: HA_MANAGE_HOME_ON_OFF
      event_data:
        state: "{{ trigger.to_state.state }}"

- alias: AUTOMATION_H07
  trigger:
    - platform: time
      at: "07:00:00"
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.night
    - delay: 0:10
    - event: HA_MANAGE_NIGHT_ON_OFF
      event_data:
        state: "{{states('input_boolean.night')}}"
    - event: AD_KAIROSHUB_STARTED

- alias: AUTOMATION_H20
  trigger:
    - platform: time
      at: "20:00:00"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.night
    - delay: 0:10
    - event: HA_MANAGE_NIGHT_ON_OFF
      event_data:
        state: "{{states('input_boolean.night')}}"
    - event: AD_KAIROSHUB_STARTED

- alias: Notte
  trigger:
  condition:
    condition: sun
    after: sunset
    before: sunrise
  action:
    service: input_boolean.turn_on
    target:
      entity_id: input_boolean.night
- alias: Giorno
  trigger:
  condition:
    condition: sun
    after: sunrise
    before: sunset
  action:
    service: input_boolean.turn_off
    target:
      entity_id: input_boolean.night