- alias: OPEN ROLLERS
  trigger:
    - platform: event
      event_type: HA_ROLLERS_ATHOME_POSITION
  action:
    event: AD_SET_ROLLERS_POS
    event_data:
      mode: athome
- alias: CLOSE ROLLERS
  trigger:
    - platform: event
      event_type: HA_ROLLERS_NOTATHOME_POSITION
  action:
    event: AD_SET_ROLLERS_POS
    event_data:
      mode: notathome
- alias: CONTROL ROLLERS
  mode: restart
  trigger:
  action:
    - event: AD_ROLLERS_CONTROL
    - delay: 00:00:30
    - condition: state
      entity_id: group.rollershutters
      state:
        - open
        - closed
    - event: AD_KAIROSHUB_NOTIFICATION
      event_data:
        sender: HUB
        ncode: "ROLLERS_{{ states('group.rollershutters') | upper }}"
        severity: NOTICE
- alias: CALIBRATE ROLLERS
  trigger:
    - platform: event
      event_type: HA_CALIBRATE_ROLLERS
  action:
    event: AD_ROLLERS_RECALIBRATE