- alias: LIGHT TURN ON
  trigger:
  action:
    event: AD_LIGHTS_ON
    event_data:
      sender: HUB

- alias: LIGHT TURN OFF
  trigger:
  action:
    event: AD_LIGHTS_OFF
    event_data:
      sender: HUB

- alias: LIGHT ZONE TOGGLE
  trigger:
    - platform: state
      entity_id:
        - light.group_lz101
        - light.group_lz102
        - light.group_lz103
        - light.group_lz104
        - light.group_lz201
        - light.group_lz202
        - light.group_lz203
        - light.group_lz301
        - light.group_lz302
        - light.group_lz303
        - light.group_lz304
      to: group.lights
  action:
    event: AD_LIGHT_ZONE_CONTROL
    event_data:
      data:
        light: "{{ trigger.entity_id }}"
        sender: HUB

- alias: COPY LIGHT SETTINGS
  trigger:
    - platform: state
      entity_id:
        - input_boolean.copy_lights_zn101
        - input_boolean.copy_lights_dayzone
        - input_boolean.copy_lights_outdoor
      from: 'off'
      to: 'on'
  action:
    event: AD_COPY_LIGHTS
    event_data:
      zone: "{{trigger.entity_id}}"

- alias: NIGHTZONE PROGRAM 1
  trigger:
    - platform: time_pattern
      minutes: /15
  condition:
    condition: state
    entity_id: input_select.zn100
    state: Programmato
  action:
    event: AD_LIGHTS_PROGRAM
    event_data:
      zone: "100"
      on_time: "{{states('input_datetime.lights_nightzone_on_program1')}}"
      off_time: "{{states('input_datetime.lights_nightzone_off_program1')}}"
      mode: "{{states('input_select.zn100_days')}}"
      sender: HUB

- alias: DAYZONE PROGRAM 1
  trigger:
    - platform: time_pattern
      minutes: /15
  condition:
    condition: state
    entity_id: input_select.zn200
    state: Programmato
  action:
    event: AD_LIGHTS_PROGRAM
    event_data:
      zone: "200"
      on_time: "{{states('input_datetime.lights_dayzone_on_program1')}}"
      off_time: "{{states('input_datetime.lights_dayzone_off_program1')}}"
      mode: "{{states('input_select.zn200_days')}}"
      sender: HUB

- alias: OUTDOOR PROGRAM 1
  trigger:
    - platform: time_pattern
      minutes: /15
  condition:
    condition: state
    entity_id: input_select.zn300
    state: Programmato
  action:
    event: AD_LIGHTS_PROGRAM
    event_data:
      zone: "300"
      on_time: "{{states('input_datetime.lights_outdoor_on_program1')}}"
      off_time: "{{states('input_datetime.lights_outdoor_off_program1')}}"
      mode: "{{states('input_select.zn300_days')}}"
      sender: HUB

- alias: NIGHTZONE SUNSET TURN OFF
  trigger:
    - platform: state
      entity_id: group.lights
      to: 'on'
      for: "{{states('input_datetime.light_offset_sunset')}}"
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: input_select.zn100
      state: Automatico
  action:
    - service: light.turn_off
      target:
        entity_id: light.group_lz100
    - event: AD_KAIROSHUB_NOTIFICATION
      event_data:
        sender: HUB
        ncode: LIGHTS_OFF
        severity: NOTICE
        kwargs:
          zone: "100"
          mode: Automatica

- alias: DAYZONE SUNSET TURN OFF
  trigger:
    - platform: state
      entity_id: group.lights
      to: 'on'
      for: "{{states('input_datetime.light_offset_sunset')}}"
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: input_select.zn200
      state: Automatico
  action:
    - service: light.turn_off
      target:
        entity_id: light.group_lz200
    - event: AD_KAIROSHUB_NOTIFICATION
      event_data:
        sender: HUB
        ncode: LIGHTS_OFF
        severity: NOTICE
        kwargs:
          zone: "200"
          mode: Automatica

- alias: OUTDOOR SUNSET TURN OFF
  trigger:
    - platform: state
      entity_id: group.lights
      to: 'on'
      for: "{{states('input_datetime.light_offset_sunset')}}"
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: state
      entity_id: input_select.zn300
      state: Automatico
  action:
    - service: light.turn_off
      target:
        entity_id: light.group_lz300
    - event: AD_KAIROSHUB_NOTIFICATION
      event_data:
        sender: HUB
        ncode: LIGHTS_OFF
        severity: NOTICE
        kwargs:
          zone: "300"
          mode: Automatica