- alias: LIGHT TURN ON
  trigger:
  action:
    event: AD_LIGHTS_ON
    event_data:
      sender: HUB

- alias: LIGHT TURN OFF
  trigger:
  action:
    event: AD_LIGHTS_OFF
    event_data:
      sender: HUB

- alias: LIGHT ZONE TOGGLE
  trigger:
    - platform: state
      entity_id:
        - light.group_lz101
        - light.group_lz102
        - light.group_lz103
        - light.group_lz104
        - light.group_lz201
        - light.group_lz202
        - light.group_lz203
        - light.group_lz301
        - light.group_lz302
        - light.group_lz303
        - light.group_lz304
      to: group.lights
  action:
    event: AD_LIGHT_ZONE_CONTROL
    event_data:
      data:
        light: "{{ trigger.entity_id }}"
        sender: HUB

- alias: COPY LIGHT SETTINGS
  trigger:
    - platform: state
      entity_id:
        - input_boolean.copy_lights_zn101
        - input_boolean.copy_lights_zn102
        - input_boolean.copy_lights_zn103
        - input_boolean.copy_lights_zn104
        - input_boolean.copy_lights_zn201
        - input_boolean.copy_lights_zn202
        - input_boolean.copy_lights_zn203
        - input_boolean.copy_lights_zn301
        - input_boolean.copy_lights_zn302
        - input_boolean.copy_lights_zn303
        - input_boolean.copy_lights_zn304
      from: "off"
      to: "on"
  action:
    event: AD_COPY_LIGHTS
    event_data:
      zone: "{{trigger.entity_id}}"

- alias: LIGHTS PROGRAM 1
  trigger:
    - platform: time_pattern
      minutes: /15
  condition:
    - condition: state
      entity_id: input_boolean.lights_program1
      state: "on"
    - condition: state
      entity_id: group.lights_program2_on
      state: "off"
  action:
    event: AD_LIGHTS_PROGRAM
    event_data:
      progId: 1
      sender: HUB

- alias: LIGHTS PROGRAM 2
  trigger:
    - platform: time_pattern
      minutes: /15
  condition:
    - condition: state
      entity_id: input_boolean.lights_program2
      state: "on"
    - condition: state
      entity_id: group.lights_program1_on
      state: "off"
  action:
    event: AD_LIGHTS_PROGRAM
    event_data:
      progId: 2
      sender: HUB

- alias: LIGHTS AUTO TURN OFF
  trigger:
    - platform: state
      entity_id: group.lights
      to: "on"
      for: "{{states('input_datetime.light_offset_sunset')}}"
  condition:
    - condition: template
      value_template: >
        {{ states('input_datetime.light_offset_sunset') != '00:00:00'}}

  action:
    - service: light.turn_off
      target:
        entity_id: group.lights

- alias: LIGHT MANUAL CHANGE
  trigger:
    - platform: state
      entity_id:
        - light.group_lz100
        - light.group_lz200
        - light.group_lz300
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state.attributes != trigger.to_state.attributes}}
    - condition: state
      entity_id:
        - input_boolean.scene_day_active
        - input_boolean.scene_athome_active
      state: "off"
  action:
    - event: "AD_MANUAL_LIGHT_CHANGE"

- alias: LIGHT SCENE CHANGE
  trigger:
    - platform: state
      entity_id:
        - input_text.lcz100_day
        - input_text.lcz101_day
        - input_text.lcz102_day
        - input_text.lcz103_day
        - input_text.lcz104_day
        - input_text.lcz200_day
        - input_text.lcz201_day
        - input_text.lcz202_day
        - input_text.lcz203_day
        - input_text.lcz300_day
        - input_text.lcz301_day
        - input_text.lcz302_day
        - input_text.lcz303_day
        - input_text.lcz304_day
        - input_text.lwz100_day
        - input_text.lwz101_day
        - input_text.lwz102_day
        - input_text.lwz103_day
        - input_text.lwz104_day
        - input_text.lwz200_day
        - input_text.lwz201_day
        - input_text.lwz202_day
        - input_text.lwz203_day
        - input_text.lwz300_day
        - input_text.lwz301_day
        - input_text.lwz302_day
        - input_text.lwz303_day
        - input_text.lwz304_day
      id: "day"
    - platform: state
      entity_id:
        - input_text.lcz100_athome
        - input_text.lcz101_athome
        - input_text.lcz102_athome
        - input_text.lcz103_athome
        - input_text.lcz104_athome
        - input_text.lcz200_athome
        - input_text.lcz201_athome
        - input_text.lcz202_athome
        - input_text.lcz203_athome
        - input_text.lcz300_athome
        - input_text.lcz301_athome
        - input_text.lcz302_athome
        - input_text.lcz303_athome
        - input_text.lcz304_athome
        - input_text.lwz100_athome
        - input_text.lwz101_athome
        - input_text.lwz102_athome
        - input_text.lwz103_athome
        - input_text.lwz104_athome
        - input_text.lwz200_athome
        - input_text.lwz201_athome
        - input_text.lwz202_athome
        - input_text.lwz203_athome
        - input_text.lwz300_athome
        - input_text.lwz301_athome
        - input_text.lwz302_athome
        - input_text.lwz303_athome
        - input_text.lwz304_athome
      id: "athome"
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state.attributes != trigger.to_state.attributes}}
  action:
    - event: "AD_SCENE_CHANGE"
      event_data:
        scene: "{{trigger.id}}"
        entity: "{{trigger.entity_id}}"

- alias: LIGHT PROGRAM CHANGE
  trigger:
    - platform: state
      entity_id:
        - input_text.lcz100_program1
        - input_text.lcz101_program1
        - input_text.lcz102_program1
        - input_text.lcz103_program1
        - input_text.lcz104_program1
        - input_text.lcz200_program1
        - input_text.lcz201_program1
        - input_text.lcz202_program1
        - input_text.lcz203_program1
        - input_text.lcz300_program1
        - input_text.lcz301_program1
        - input_text.lcz302_program1
        - input_text.lcz303_program1
        - input_text.lcz304_program1
        - input_text.lwz100_program1
        - input_text.lwz101_program1
        - input_text.lwz102_program1
        - input_text.lwz103_program1
        - input_text.lwz104_program1
        - input_text.lwz200_program1
        - input_text.lwz201_program1
        - input_text.lwz202_program1
        - input_text.lwz203_program1
        - input_text.lwz300_program1
        - input_text.lwz301_program1
        - input_text.lwz302_program1
        - input_text.lwz303_program1
        - input_text.lwz304_program1
      id: "program1"
    - platform: state
      entity_id:
        - input_text.lcz100_program2
        - input_text.lcz101_program2
        - input_text.lcz102_program2
        - input_text.lcz103_program2
        - input_text.lcz104_program2
        - input_text.lcz200_program2
        - input_text.lcz201_program2
        - input_text.lcz202_program2
        - input_text.lcz203_program2
        - input_text.lcz300_program2
        - input_text.lcz301_program2
        - input_text.lcz302_program2
        - input_text.lcz303_program2
        - input_text.lcz304_program2
        - input_text.lwz100_program2
        - input_text.lwz101_program2
        - input_text.lwz102_program2
        - input_text.lwz103_program2
        - input_text.lwz104_program2
        - input_text.lwz200_program2
        - input_text.lwz201_program2
        - input_text.lwz202_program2
        - input_text.lwz203_program2
        - input_text.lwz300_program2
        - input_text.lwz301_program2
        - input_text.lwz302_program2
        - input_text.lwz303_program2
        - input_text.lwz304_program2
      id: "program2"
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state.attributes != trigger.to_state.attributes}}
    - condition: state
      entity_id: input_boolean.scene_day_active
      state: "off"
    - condition: state
      entity_id: input_boolean.scene_athome_active
      state: "off"
  action:
    - event: "AD_SCENE_CHANGE"
      event_data:
        program: "{{trigger.id}}"
        entity: "{{trigger.entity_id}}"
