- alias: DAY NIGHT SCENE MANUAL
  trigger:
  action:
    - service: input_boolean.toggle
      target:
        entity_id: input_boolean.night
    - event: AD_SCENES_DAY_NIGHT
      event_data:
        state: "{{ states('input_boolean.night') }}"
        mode: Manuale
        sender: HUB

- alias: NIGHT SCENE PROGRAMMED
  trigger:
    - platform: time
      at: input_datetime.scene_day_off
  condition:
    - condition: state
      state: Programmato
      entity_id: input_select.scene_day
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.night
    - event: AD_SCENES_DAY_NIGHT
      event_data:
        state: "{{ states('input_boolean.night') }}"
        mode: Programmato
        sender: HUB

- alias: DAY SCENE PROGRAMMED
  trigger:
    - platform: time
      at: input_datetime.scene_day_on
  condition:
    - condition: state
      state: Programmato
      entity_id: input_select.scene_day
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.night
    - event: AD_SCENES_DAY_NIGHT
      event_data:
        state: "{{ states('input_boolean.night') }}"
        mode: Programmato
        sender: HUB

- alias: NIGHT SCENE AUTO
  trigger:
    - platform: time
      at: "07:00:00"
  condition:
    - condition: state
      state: Automatico
      entity_id: input_select.scene_day
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.night
    - event: AD_SCENES_DAY_NIGHT
      event_data:
        state: "{{ states('input_boolean.night') }}"
        mode: Automatico
        sender: HUB

- alias: DAY SCENE AUTO
  trigger:
    - platform: time
      at: "20:00:00"
  condition:
    - condition: state
      state: Automatico
      entity_id: input_select.scene_day
  action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.night
    - event: AD_SCENES_DAY_NIGHT
      event_data:
        state: "{{ states('input_boolean.night') }}"
        mode: Automatico
        sender: HUB
