- platform: template
  sensors:
    tv2011_state:
      value_template: >-
        {% if (now() - states.sensor.TV2011_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv2012_state:
      value_template: >-
        {% if (now() - states.sensor.TV2012_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv2021_state:
      value_template: >-
        {% if (now() - states.sensor.TV2021_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv2022_state:
      value_template: >-
        {% if (now() - states.sensor.TV2022_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv2031_state:
      value_template: >-
        {% if (now() - states.sensor.TV2031_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv2032_state:
      value_template: >-
        {% if (now() - states.sensor.TV2032_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
