- platform: template
  sensors:
    tv1011_state:
      value_template: >-
        {% if (now() - states.sensor.TV1011_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv1012_state:
      value_template: >-
        {% if (now() - states.sensor.TV1012_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv1021_state:
      value_template: >-
        {% if (now() - states.sensor.TV1021_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv1022_state:
      value_template: >-
        {% if (now() - states.sensor.TV1022_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv1031_state:
      value_template: >-
        {% if (now() - states.sensor.TV1031_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv1032_state:
      value_template: >-
        {% if (now() - states.sensor.TV1032_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv1041_state:
      value_template: >-
        {% if (now() - states.sensor.TV1041_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
    tv1042_state:
      value_template: >-
        {% if (now() - states.sensor.TV1042_lastupdate.last_changed).total_seconds() | round(0) > 3600 %}
          offline
        {% else %}
          online
        {% endif %}
