- platform: template
  sensors:
    heater_auto:
      friendly_name: "Programma caldo"
      value_template: >-
        {% if is_state('input_boolean.heater_program1', 'on') or is_state('input_boolean.heater_program2', 'on') or is_state('input_boolean.heater_program3', 'on') or is_state('input_boolean.heater_program4', 'on') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz100_state:
      friendly_name: "Stato Luci Zona Notte"
      value_template: >-
        {% if is_state('binary_sensor.lz101_state', 'on') or is_state('binary_sensor.lz102_state', 'on') or is_state('binary_sensor.lz103_state', 'on') or is_state('binary_sensor.lz104_state', 'on') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz101_state:
      friendly_name: "Stato Luci Zona 101"
      value_template: >-
        {% if is_state('sensor.lcz101_state', 'online') or is_state('sensor.lwz101_state', 'online') or is_state('sensor.lz101_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz102_state:
      friendly_name: "Stato Luci Zona 102"
      value_template: >-
        {% if is_state('sensor.lcz102_state', 'online') or is_state('sensor.lwz102_state', 'online') or is_state('sensor.lz102_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz103_state:
      friendly_name: "Stato Luci Zona 103"
      value_template: >-
        {% if is_state('sensor.lcz103_state', 'online') or is_state('sensor.lwz103_state', 'online') or is_state('sensor.lz103_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz104_state:
      friendly_name: "Stato Luci Zona 104"
      value_template: >-
        {% if is_state('sensor.lcz104_state', 'online') or is_state('sensor.lwz104_state', 'online') or is_state('sensor.lz104_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz200_state:
      friendly_name: "Stato Luci Zona Giorno"
      value_template: >-
        {% if is_state('binary_sensor.lz201_state', 'on') or is_state('binary_sensor.lz202_state', 'on') or is_state('binary_sensor.lz203_state', 'on') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz201_state:
      friendly_name: "Stato Luci Zona 201"
      value_template: >-
        {% if is_state('sensor.lcz201_state', 'online') or is_state('sensor.lwz201_state', 'online') or is_state('sensor.lz201_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz202_state:
      friendly_name: "Stato Luci Zona 202"
      value_template: >-
        {% if is_state('sensor.lcz202_state', 'online') or is_state('sensor.lwz202_state', 'online') or is_state('sensor.lz202_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz203_state:
      friendly_name: "Stato Luci Zona 203"
      value_template: >-
        {% if is_state('sensor.lcz203_state', 'online') or is_state('sensor.lwz203_state', 'online') or is_state('sensor.lz203_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz300_state:
      friendly_name: "Stato Luci Esterno"
      value_template: >-
        {% if is_state('binary_sensor.lz301_state', 'on') or is_state('binary_sensor.lz302_state', 'on') or is_state('binary_sensor.lz303_state', 'on') or is_state('binary_sensor.lz304_state', 'on') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz301_state:
      friendly_name: "Stato Luci Zona 301"
      value_template: >-
        {% if is_state('sensor.lcz301_state', 'online') or is_state('sensor.lwz301_state', 'online') or is_state('sensor.lz301_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz302_state:
      friendly_name: "Stato Luci Zona 302"
      value_template: >-
        {% if is_state('sensor.lcz302_state', 'online') or is_state('sensor.lwz302_state', 'online') or is_state('sensor.lz302_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz303_state:
      friendly_name: "Stato Luci Zona 303"
      value_template: >-
        {% if is_state('sensor.lcz303_state', 'online') or is_state('sensor.lwz303_state', 'online') or is_state('sensor.lz303_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}
- platform: template
  sensors:
    lz304_state:
      friendly_name: "Stato Luci Zona 304"
      value_template: >-
        {% if is_state('sensor.lcz304_state', 'online') or is_state('sensor.lwz304_state', 'online') or is_state('sensor.lz304_state', 'online') %}
          on
        {% else %}
          off
        {% endif %}